### ISSUE TITLE
Degree Progress Bar

### ISSUE THREAD

**Issue by PeterETschaekofske** [athena-scheduler/athena#103]
We need to decide on implementing the degree progress bar for the home page. We had some ideas on how it should it look but we should also consider on if we want it at all.

**Comment by nlowe** [comment]
I vote we nuke this. You can register for multiple programs. In that case, we'd probably need a separate page to display this information. @nchurchill brought up a good point: The only way we can calculate progress is based on the number of courses completed / left. This doesn't take into account credit hours and isn't very accurate.

**Comment by nchurchill** [comment]
I voted along with Nathan that this should probably be removed as it is not an overly accurate representation in my eyes of your degree completion. It is an interesting idea but there are so many factors that could play into it that I'm not of the thought that it is something that we should try to implement.
