### ISSUE TITLE
link up the scheduler to the api

### ISSUE THREAD

**Issue by nchurchill** [athena-scheduler/athena#46]
We need to link up the scheduler to the real data in the databases and to the apis.

**Comment by PeterETschaekofske** [comment]
We need to make the feature of making a new  schedule that this is for building a new schedule for the next semester only. Perhaps making the button say "Begin Scheduling for next semester" or something along those lines.

**Comment by nlowe** [comment]
@PeterETschaekofske We'll take care of that in #66

**Comment by nlowe** [comment]
Also, don't allow a user to enroll in a class if the timeslot conflicts

**Comment by nlowe** [comment]
Blocked by #76
