### ISSUE TITLE
Login expires too quickly

### ISSUE THREAD

**Issue by nlowe** [athena-scheduler/athena#61]
The session appears to expire quickly even if you're interacting with the site. We need to find a way to increase this and not kick people off if they're actively doing things.

**Comment by nlowe** [comment]
There's also an issue where we can get null refs because the application thinks a user is authenticated but they have a cookie that doesn't correspond to the current database. That should probably be fixed as well.

**Comment by nlowe** [comment]
Unless I'm dumb I feel like this is still happening...

**Comment by nlowe** [comment]
Ah, I think this is actually because we're not storing the security stamp for users via Identity, [which appears to be required](https://github.com/aspnet/Identity/issues/1389#issuecomment-324235966).

**Comment by 54414D49TAMI** [comment]
@nlowe 
I am having similar issue in my project. Can you please shed some light on which line of codes from authentication middleware that detect user's cookie " doesn't correspond to the current database"?

**Comment by nlowe** [comment]
@54414D49TAMI Sure. I'm still not certain I fully understand how this works, but here's what I can gather:

The default Security Stamp Validator calls out to the sign-in-manager to validate the stamp for the user:

https://github.com/aspnet/Identity/blob/8cbda5a23dd594116fcd2f60c486d15fa50051af/src/Microsoft.AspNetCore.Identity/SecurityStampValidator.cs#L44-L98

The default sign-in-manager pulls the security stamp from the user identity and compares it to the one stored by the User Manager:

https://github.com/aspnet/Identity/blob/8cbda5a23dd594116fcd2f60c486d15fa50051af/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L209-L233

Note that the user manager must support getting security stamps or this will fail. If you are using a custom user manager, it must implement `IUserSecurityStampStore<TUser>`

By default, this happens every 30 minutes: 

https://github.com/aspnet/Identity/blob/8cbda5a23dd594116fcd2f60c486d15fa50051af/src/Microsoft.AspNetCore.Identity/SecurityStampValidatorOptions.cs#L14-L20

Because I was implementing my own user store, I missed the security stamp requirement. Thus, every time the security stamp was checked, I would get signed out since ASP.NET couldn't guarantee my login was still valid.

**Comment by 54414D49TAMI** [comment]
@nlowe Thanks. Your info has been helpful and I solved my problems.

**Comment by aguayUmbt** [comment]
@nlowe 
I've got the same problem but don't understand your solution, what did you had to your code so you ExpireTimeSpan won't be overwritten?
![asd](https://user-images.githubusercontent.com/39703106/43083520-bb7dc010-8e64-11e8-8d93-3f61d61dc017.PNG)

**Comment by 54414D49TAMI** [comment]
@aguayUmbt 
Hi. What are your codes and approaches, mostly same? SSO, Asp.Net version etc..

The solution may vary. If you have codes in GitHub, please address it.

**Comment by aguayUmbt** [comment]
I don't have clues why, but it ended up working... It seems to last more than 30mins now so I just hope it will last the 12hours i've set.
